# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'weather_app.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5 import QtCore, QtGui, QtWidgets
import requests
import time
from PyQt5.QtWidgets import QMessageBox


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(516, 476)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("D:/Picture/space/images.jpg"),
        QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Dialog.setWindowIcon(icon)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.root = QtWidgets.QFrame(Dialog)
        self.root.setStyleSheet("background-color: rgb(255, 251, 133);")
        self.root.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.root.setFrameShadow(QtWidgets.QFrame.Raised)
        self.root.setObjectName("root")
        self.lbl_weather = QtWidgets.QLabel(self.root)
        self.lbl_weather.setGeometry(QtCore.QRect(190, 10, 111, 31))
        self.lbl_weather.setStyleSheet("font: 14pt \"Tahoma\";\n"
"\n"
"")
        self.lbl_weather.setObjectName("lbl_weather")
        self.lbl_photo = QtWidgets.QLabel(self.root)
        self.lbl_photo.setGeometry(QtCore.QRect(130, 50, 231, 121))
        self.lbl_photo.setStyleSheet("border: 3px solid blue;\n"
"                                    border-radius: 8px;")
        self.lbl_photo.setText("")
        self.lbl_photo.setPixmap(QtGui.QPixmap("D:/Picture/space/images.jpg"))
        self.lbl_photo.setObjectName("lbl_photo")
        self.lbl_Enter = QtWidgets.QLabel(self.root)
        self.lbl_Enter.setGeometry(QtCore.QRect(20, 190, 161, 41))
        self.lbl_Enter.setObjectName("lbl_Enter")
        self.enter_city = QtWidgets.QLineEdit(self.root)
        self.enter_city.setGeometry(QtCore.QRect(190, 200, 181, 31))
        self.enter_city.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.enter_city.setObjectName("enter_city")
        self.btn_click = QtWidgets.QPushButton(self.root,clicked=lambda:self.weather_city_app())
        self.btn_click.setGeometry(QtCore.QRect(380, 200, 111, 31))
        self.btn_click.setStyleSheet("background-color: rgb(147, 254, 255);\n"
"color: rgb(0, 0, 0);")
        self.btn_click.setObjectName("btn_click")
        self.lbl_result = QtWidgets.QLabel(self.root)
        self.lbl_result.setGeometry(QtCore.QRect(20, 260, 471, 201))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(12)
        self.lbl_result.setFont(font)
        self.lbl_result.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lbl_result.setText("")
        self.lbl_result.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_result.setObjectName("lbl_result")
        self.verticalLayout.addWidget(self.root)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.lbl_weather.setText(_translate("Dialog", "Weather App"))
        self.lbl_Enter.setText(_translate("Dialog", "Enter city weather you want : "))
        self.btn_click.setText(_translate("Dialog", "click me"))

    def weather_city_app(self):

        try:
            city=self.enter_city.text()
            myApi="http://api.openweathermap.org/data/2.5/weather?q="+city+"&appid=0682a72eeeaa1a1e6c7df1f7fc49cc07"
            json_data=requests.get(myApi).json()
            temp=int(json_data["main"]["temp"]-273.15)
            min_temp=int(json_data["main"]["temp_min"]-273.15)
            max_temp=int(json_data["main"]["temp_max"]-273.15)
            pressure=json_data["main"]["pressure"]
            humidity=json_data["main"]["humidity"]
            speed=json_data["wind"]["speed"]
            sunrise=time.strftime("%I:%M:%S",time.gmtime(json_data["sys"]["sunrise"]-21600))
            sunset=time.strftime("%I:%M:%S",time.gmtime(json_data["sys"]["sunset"]-21600))

            final_info=str(json_data["weather"][0]["main"])+"\n"+str(temp)+"°C"
            final_data="\n"+"Max temp : "+str(max_temp) +"\n"+"Min temp : "+str(min_temp)+"\n"+"Pressure : "+str(pressure)+"\n"+"Humidity : "+str(humidity)+"\n"+"Speed : "+str(speed)+"\n"+"Sunrise : "+str(sunrise)+"\n"+"Sunset : "+str(sunset)

            complet_data=final_info+final_data

            self.lbl_result.setText(complet_data)
        except KeyError:
            info_msg = QMessageBox()
            info_msg.setWindowTitle("Information message box")
            info_msg.setText("You must enter a city name")
            info_msg.setIcon(QMessageBox.Information)

            x = info_msg.exec_()

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
